# -*- coding: utf-8 -*-
"""Handle Missing Data : fillna, dropna, interpolate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eDKF3l3rJSq8EGbQfeWsjX9vPq4MHabm

**Import a data and convert into dataframe**
"""

import pandas as pd

from google.colab import files
files.upload()

df = pd.read_csv('oil-company-doe.csv')
df

"""## **1. fillna method**"""

df1 = df.fillna(0)
df1

"""### **Sometimes having 0 is not a better guess**"""

df1 = df.fillna({'x1':0, 'x2':0, 'x3':'No', 'x4':0, 'y':0})
df1

"""### **Still didnt satisfied the result use "ffill" or "bfill" method**"""

df1 = df.fillna(method="ffill")
df1

df1 = df.fillna(method="bfill")
df1

"""## **2. Interpolate Method**

**For a better guessing**
"""

df1 = df.interpolate()
df1

"""## **3. Dropna Method**"""

#Sometimes based on situation i need to drop the missing values from my dataset

df1 = df.dropna()
df1